import type { Scenario } from './types';

export const SCENARIOS: Scenario[] = [
  {
    id: 'slow-start',
    index: '01',
    title: 'Slow Start',
    story: 'Exponential cwnd growth from 1 MSS until first loss.',
    variant: 'newreno',
    bandwidth: '1Mbps',
    delay: '10ms',
    queueSize: 20,
    duration: 20,
  },
  {
    id: 'congestion-collapse',
    index: '02',
    title: 'Congestion Collapse',
    story: 'Aggressive drops force a sawtooth crash. Tahoe with a small queue.',
    variant: 'tahoe',
    bandwidth: '512Kbps',
    delay: '50ms',
    queueSize: 5,
    duration: 20,
  },
  {
    id: 'high-bdp',
    index: '03',
    title: 'High BDP Pipe',
    story: 'Long-delay link. Hybla compensates for high RTT.',
    variant: 'hybla',
    bandwidth: '1Mbps',
    delay: '100ms',
    queueSize: 50,
    duration: 20,
  },
  {
    id: 'bufferbloat',
    index: '04',
    title: 'Bufferbloat',
    story: 'Oversized queue. Throughput holds, latency explodes.',
    variant: 'newreno',
    bandwidth: '1Mbps',
    delay: '10ms',
    queueSize: 200,
    duration: 20,
  },
  {
    id: 'fair-recovery',
    index: '05',
    title: 'Fair Recovery',
    story: 'Westwood uses bandwidth estimates on loss recovery.',
    variant: 'westwood',
    bandwidth: '1Mbps',
    delay: '10ms',
    queueSize: 20,
    duration: 20,
  },
  {
    id: 'custom',
    index: '06',
    title: 'Custom',
    story: 'Tune every parameter. Pick any variant.',
    variant: null,
    bandwidth: '1Mbps',
    delay: '10ms',
    queueSize: 20,
    duration: 20,
    isCustom: true,
  },
];

export const DEFAULT_SCENARIO_ID = 'slow-start';